name: wasanbon_elements
version: 0.1.3
description: A library useful for applications or for sharing on pub.dartlang.org.
dependencies:
  browser: any
  polymer: '>1.0.0-rc.2'
  polymer_elements: '>1.0.0-rc.5'
  web_components: ^0.12.0
  reflectable: ^0.3.0
  wasanbon_xmlrpc:
    git : https://github.com/sugarsweetrobotics/wasanbon_xmlrpc.dart
dev_dependencies:
  unittest: any
transformers:
- web_components:
    entry_points: web/test_polymer.html
- reflectable:
    entry_points: web/test_polymer.dart
- $dart2js:
    $include: web/index.html_bootstrap.dart
